In [1]:
import sys
sys.path.append('/Users/victoria/Documents/Scripts/Python/DGL-PTM/dgl_ptm')
import dgl_ptm
import os
os.environ["DGLBACKEND"] = "pytorch"

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
model = dgl_ptm.PovertyTrapModel(model_identifier='default')

In [3]:
model.set_model_parameters(default=True)
print(model.steering_parameters)

{'npath': './agent_data.zarr', 'epath': './edge_data', 'ndata': ['all_except', ['a_table']], 'edata': ['all'], 'mode': 'xarray', 'wealth_method': 'singular_transfer', 'income_method': 'pseudo_income_generation', 'tech_gamma': tensor([0.3000, 0.3500, 0.4500]), 'tech_cost': tensor([0.0000, 0.1500, 0.6500]), 'consume_method': 'pseudo_consumption', 'adapt_m': tensor([0.0000, 0.5000, 0.9000]), 'adapt_cost': tensor([0.0000, 0.2500, 0.4500]), 'depreciation': 0.6, 'discount': 0.95, 'm_theta_dist': {'type': 'multinomial', 'parameters': [[0.01, 0.1, 0.79, 0.1], [0.1, 0.5, 0.8, 1]], 'round': False, 'decimals': None}, 'del_prob': 0.05, 'ratio': 0.1, 'weight_a': 0.69, 'weight_b': 35, 'truncation_weight': 1e-10, 'step_type': 'default'}


In [4]:
model.initialize_model()

In [5]:
model.run()

performing step 1 of 20
dst node 92 is an end node
no FoF link possible for src dst nodes 0 and 92.
created 0 of 1 links requested
gets to data collection
performing step 2 of 20
creating bidirectional link between nodes 91 (src) and tensor([8]) (dst)
created 1 of 1 links requested
gets to data collection
performing step 3 of 20
creating bidirectional link between nodes 80 (src) and tensor([59]) (dst)
created 1 of 1 links requested
gets to data collection
performing step 4 of 20
creating bidirectional link between nodes 52 (src) and tensor([66]) (dst)
created 1 of 1 links requested
gets to data collection
performing step 5 of 20
dst node 50 is an end node
no FoF link possible for src dst nodes 29 and 50.
created 0 of 1 links requested
gets to data collection
performing step 6 of 20
creating bidirectional link between nodes 44 (src) and tensor([0]) (dst)
created 1 of 1 links requested
gets to data collection
performing step 7 of 20
creating bidirectional link between nodes 18 (src) and 

In [6]:
model = dgl_ptm.PovertyTrapModel(model_identifier='test')

In [7]:
import torch
model.set_model_parameters(default=False, **{'steering_parameters': {'npath':'./agent_data.zarr',
                            'epath':'./edge_data', 
                            'ndata':['all_except',['a_table']],
                            'edata':['all'],
                            'mode':'xarray',
                            'wealth_method':'singular_transfer',
                            'income_method':'income_generation',
                            'tech_gamma': torch.tensor([0.3,0.35,0.45]),
                            'tech_cost': torch.tensor([0,0.15,0.65]),
                            'consume_method':'optimized_consumption',
                            'adapt_m':torch.tensor([0,0.5,0.9]),
                            'adapt_cost':torch.tensor([0,0.25,0.45]),
                            'depreciation': 0.6,
                            'discount': 0.95,
                            'm_theta_dist': {'type':'multinomial','parameters':[[0.01 ,0.1, 0.79, 0.1],[0.1, 0.5, 0.8, 1]],'round':False,'decimals':None},
                            'del_prob':0.05,
                            'ratio':0.1,
                            'weight_a':0.69,
                            'weight_b':35, 
                            'truncation_weight':1.0e-10,
                            'step_type': 'custom'}})

print(model.number_agents)  
print(model.steering_parameters)                        

100
{'npath': './agent_data.zarr', 'epath': './edge_data', 'ndata': ['all_except', ['a_table']], 'edata': ['all'], 'mode': 'xarray', 'wealth_method': 'singular_transfer', 'income_method': 'income_generation', 'tech_gamma': tensor([0.3000, 0.3500, 0.4500]), 'tech_cost': tensor([0.0000, 0.1500, 0.6500]), 'consume_method': 'optimized_consumption', 'adapt_m': tensor([0.0000, 0.5000, 0.9000]), 'adapt_cost': tensor([0.0000, 0.2500, 0.4500]), 'depreciation': 0.6, 'discount': 0.95, 'm_theta_dist': {'type': 'multinomial', 'parameters': [[0.01, 0.1, 0.79, 0.1], [0.1, 0.5, 0.8, 1]], 'round': False, 'decimals': None}, 'del_prob': 0.05, 'ratio': 0.1, 'weight_a': 0.69, 'weight_b': 35, 'truncation_weight': 1e-10, 'step_type': 'custom'}


In [8]:
model.initialize_model()

In [9]:
model.run()

performing step 1 of 20
dst node 91 is an end node
no FoF link possible for src dst nodes 3 and 91.
created 0 of 1 links requested
tensor([3.2029e+00, 5.9491e-01, 8.2273e-01, 3.9132e-03, 9.7171e-01, 3.2698e+00,
        5.4570e-01, 3.8353e+00, 1.3132e-03, 9.0159e-01, 1.5566e-01, 1.5950e+00,
        4.0562e+00, 1.1643e+00, 6.7009e-04, 9.0837e-01, 1.0512e+00, 2.4808e+00,
        1.3334e+00, 5.9333e+00, 1.9972e+00, 2.9975e-01, 7.8517e-01, 1.5069e+00,
        2.2790e-01, 6.8250e-02, 3.7630e+00, 2.7318e+00, 2.1619e+00, 8.2732e-01,
        6.4566e-01, 2.7197e+00, 5.3587e+00, 3.1591e-02, 1.0662e+00, 3.7420e+00,
        3.3982e+00, 7.6127e-02, 3.0553e+00, 2.4880e+00, 2.4515e+00, 4.0384e+00,
        7.7789e-01, 3.0177e+00, 1.7469e+00, 1.7339e+00, 8.2605e-04, 2.5885e+00,
        8.8006e-01, 3.4454e-02, 2.3518e+00, 1.4662e-01, 1.2753e+00, 3.8384e+00,
        2.0337e+00, 1.1884e-02, 2.9275e-03, 5.9572e-01, 2.3796e-01, 3.2560e+00,
        5.3400e-03, 1.3972e+00, 2.3045e+00, 7.1039e-01, 2.9268e+00, 4

In [10]:
import torch
import numpy as np
TechTable =  np.array([[0.3,0],[0.35,0.15],[0.45, 0.65]])
wealth=torch.tensor([ 6.4072, 17.6514,  8.5695, 27.9308, 13.7166])
alpha=torch.tensor([1.0997, 0.9967, 1.0678, 0.9097, 1.0579])
gamma = torch.tensor([0.3,0.35,0.45])
cost = torch.tensor([0,0.15,0.65])

income,index = torch.max((alpha[:,None]*wealth[:,None]**TechTable[:,0] - TechTable[:,1]), axis=1)
income=income.to(torch.float32)

print(income)
print(index)


income,tech_index = torch.max((alpha[:,None]*wealth[:,None]**gamma - cost), axis=1)

print(income.dtype)
print(index)

tensor([1.9567, 2.9776, 2.1575, 3.4204, 2.7872])
tensor([1, 2, 2, 2, 2])
torch.float32
tensor([1, 2, 2, 2, 2])


In [11]:
def sample_distribution_tensor(type, distParameters, nSamples, round=False, decimals=None):
    """
    create and return samples from different distributions

    :param type: Type of distribution to sample
    :param distParameters: array of parameters as required/supported by requested distribution type
    :param nSamples: number of samples to return (as 1d tensor)
    :param round: optional, whether the samples are to be rounded
    :param decimals: optional, required if round is specified. decimal places to round to
    """
    if type == 'uniform':
        dist = torch.distributions.uniform.Uniform(torch.tensor(distParameters[0]),torch.tensor(distParameters[1])).sample(torch.tensor([nSamples]))
    elif type == 'normal':
        dist = torch.distributions.normal.Normal(torch.tensor(distParameters[0]),torch.tensor(distParameters[1])).sample(torch.tensor([nSamples]))
    elif type == 'bernoulli':
        dist = torch.distributions.bernoulli.Bernoulli(probs=distParameters[0],logits=distParameters[1],validate_args=None).sample(torch.tensor([nSamples]))
    elif type == 'multinomial':
        dist = torch.gather(torch.Tensor(distParameters[1]), 0, torch.multinomial(torch.tensor(distParameters[0]), nSamples, replacement=True))

    else:
        raise NotImplementedError('Currently only uniform, normal, multinomial, and bernoulli distributions are supported')

    if round:
        if decimals == None:
            raise ValueError('rounding requires decimals of rounding accuracy to be specified')
        else:
            return torch.round(dist,decimals=decimals)
    else:
        return dist

theta_dist = {'type':'multinomial','parameters':[[0.01 ,0.1, 0.79, 0.1],[0.1, 0.5, 0.8, 1]],'round':False,'decimals':None} 
theta_vals = torch.tensor([0.1, 0.5, 0.8, 1])
capital_dist = {'type':'uniform','parameters':[0.1,10.],'round':False,'decimals':None}


agentsCapital = sample_distribution_tensor(capital_dist['type'],capital_dist['parameters'],10,capital_dist['round'],decimals=capital_dist['decimals'])
print(agentsCapital)
modelTheta = sample_distribution_tensor(theta_dist['type'],theta_dist['parameters'],10,round=theta_dist['round'],decimals=theta_dist['decimals'])
print(modelTheta[1])


tensor([3.6091, 2.0877, 2.1235, 1.1489, 7.8204, 9.6203, 7.9892, 2.9878, 7.7790,
        0.8866])
tensor(0.8000)


In [12]:
tech_gamma=torch.tensor([0.3,0.35,0.45])
tech_cost=torch.tensor([0,0.15,0.65])
α=1
k=2



f = []
for i in range(tech_gamma.size(dim=0)): 
    #in the end, they may need their own tech tables
    entry = α * k**tech_gamma[i] - tech_cost[i]
    f.append(entry)
print(f)
entry = α * k**tech_gamma - tech_cost
print(entry)


[tensor(1.2311), tensor(1.1246), tensor(0.7160)]
tensor([1.2311, 1.1246, 0.7160])


In [13]:
torch.stack([tech_gamma,tech_cost]).repeat(4,1,1)


tensor([[[0.3000, 0.3500, 0.4500],
         [0.0000, 0.1500, 0.6500]],

        [[0.3000, 0.3500, 0.4500],
         [0.0000, 0.1500, 0.6500]],

        [[0.3000, 0.3500, 0.4500],
         [0.0000, 0.1500, 0.6500]],

        [[0.3000, 0.3500, 0.4500],
         [0.0000, 0.1500, 0.6500]]])

In [14]:
data={'a':0,'b':4,'c':12}
params={'steering_parameters':{'m_theta_dist': {'type':'multinomial','parameters':[[0.01 ,0.1, 0.79, 0.1],[0.1, 0.5, 0.8, 1]],'round':False,'decimals':None},
                            'del_prob':0.05},'ndtata':['all']}

print(params['steering_parameters']['m_theta_dist']['parameters'][1])


def printdata(ndata):
    if ndata == ['all']:
        ndata = list(data.keys())

    if ndata[0] == 'allexcept':
        ndata = list(data.keys() - ndata[1])
    print(ndata)


printdata(['all'])
printdata(['allexcept',['a']])
printdata(['allexcept',['a','c']])

[0.1, 0.5, 0.8, 1]
['a', 'b', 'c']
['b', 'c']
['b']


In [15]:
import numpy as np
from scipy.interpolate import interp1d
from scipy.optimize import minimize_scalar

def income_function(k,α,tech): 
    f=α * k**tech['gamma'] - tech['cost']
    return torch.max(f)


class BellmanEquation:
    #Adapted from: https://python.quantecon.org/optgrowth.html
    def __init__(self,
                u,            # utility function
                f,            # production function
                k,            # current state k_t
                θ,            # given shock factor θ
                σ,            # risk averseness
                α,            # human capital
                i_a,          # adaptation investment
                m,            # protection multiplier
                β,            # discount factor
                𝛿,            # depreciation factor 
                tech):       # adaptation table 
                #name="BellmanNarrowExtended"
                

        self.u, self.f, self.k, self.β, self.θ, self.𝛿, self.σ, self.α, self.i_a, self.m, self.tech = u, f, k, β, θ, 𝛿, σ, α, i_a, m, tech

        # Set up grid
        
        startgrid=np.array([1.0e-7,1,2,3,4,5,6,7,8,9,10,k+100])

        ind=np.searchsorted(startgrid, k)
        self.grid=np.concatenate((startgrid[:ind],np.array([k*0.99999, k]),
                                startgrid[ind:]))

        self.grid=self.grid[self.grid>i_a]

        # Identify target state k
        self.index = np.searchsorted(self.grid, k)-1
    def value(self, c, y, v_array):
        """
        Right hand side of the Bellman equation.
        """

        u, f, β, θ, 𝛿, σ, α, i_a, m, tech = self.u, self.f, self.β, self.θ, self.𝛿, self.σ, self.α, self.i_a, self.m, self.tech

        v = interp1d(self.grid, v_array, bounds_error=False, 
                    fill_value="extrapolate")
        return u(c,σ) + β * v((θ + m * (1-θ)) * (f(y,α,tech) - c - i_a + (1 - 𝛿) * y))


def _optimized_wealth_consumption(model_graph, model_params):
    
   


    def maximize(g, a, b, args):
        """
        From: https://python.quantecon.org/optgrowth.html (similar example 
        https://macroeconomics.github.io/Dynamic%20Programming.html#.ZC13-exBy3I)
        Maximize the function g over the interval [a, b].

        The maximizer of g on any interval is
        also the minimizer of -g.  The tuple args collects any extra
        arguments to g.

        Returns the maximum value and the maximizer.
        """

        objective = lambda x: -g(x, *args)
        result = minimize_scalar(objective, bounds=(a, b), method='bounded')
        maximizer, maximum = result.x, -result.fun
        return maximizer, maximum

    def utility(c, σ, type="isoelastic"):
        if type == "isoelastic":
            if σ ==1:
                return np.log(c)
            else:
                return (c**(1-σ)-1)/(1-σ)

        else:
            print("Unspecified utility function!!!")


    def update_bellman(v, bell):
        """
        From: https://python.quantecon.org/optgrowth.html (similar example
        https://macroeconomics.github.io/Dynamic%20Programming.html#.ZC13-exBy3I)
        
        The Bellman operator.  Updates the guess of the value function
        and also computes a v-greedy policy.

        * bell is an instance of Bellman equation
        * v is an array representing a guess of the value function

        """
        v_new = np.empty_like(v)
        v_greedy = np.empty_like(v)
        
        for i in range(len(bell.grid)):
            y = bell.grid[i]
            # Maximize RHS of Bellman equation at state y
            
            c_star, v_max = maximize(bell.value, min([1e-8,y*0.00001]), 
                                    y-bell.i_a, (y, v))
            #VMG HELP! can anyone check that (1) subtracting i_a and 
            # (2) omitting any grid values less than i_a 
            # will not be problematic? The only thing I can come up with
            # is if i_a is greater than k*0.99999
            # which_bellman() now accounts for that case. Whole thing 
            # could use refinement.
        
            v_new[i] = v_max
            v_greedy[i] = c_star

        return v_greedy, v_new


    def which_bellman(agentinfo):
        """
        Solves bellman for each affordable adaptation option.
        """
        feasible=[]

        for option in torch.transpose(agentinfo['adapt'],0,1):
            if option[1]>=((income_function(agentinfo['k'],agentinfo['α'],tech={'gamma':model_params['tech_gamma'],'cost':model_params['tech_cost']})+(1 - model_params['depreciation'])*agentinfo['k'])*.99998):
                # ensures that the gridpoint
                # just below k, k*0.99999, is included
                pass
            else:
                #  print(f'working theta = {agentinfo.θ + option[0] *\
                #  (1-agentinfo.θ)}, i_a= {option[1]}, k= {agentinfo.k}')
                c,v=solve_bellman(BellmanEquation(u=utility, 
                                f=income_function, k=agentinfo['k'], 
                                θ=agentinfo['θ'], σ=agentinfo['σ'], 
                                α=agentinfo['α'], i_a=option[1].numpy(),m=option[0],
                                β=model_params['discount'], 𝛿=model_params['depreciation'],
                                tech={'gamma':model_params['tech_gamma'],'cost':model_params['tech_cost']}))
                feasible.append([v,c,option[1],option[0]])

        best=min(feasible)

        return best[1],best[2],best[3]

    def solve_bellman(bell,
                    tol=1,
                    min_iter=10,
                    max_iter=1000,
                    verbose=False):
        """
        From: https://python.quantecon.org/optgrowth.html (similar example
        https://macroeconomics.github.io/Dynamic%20Programming.html#.ZC13-exBy3I)
        
        Solve model by iterating with the Bellman operator.

        """


        # Set up loop

        v = bell.u(bell.grid,bell.σ)  # Initial condition
        i = 0
        error = tol + 1

        while (i < max_iter and error > tol) or (i < min_iter):
            v_greedy, v_new = update_bellman(v, bell)
            error = np.abs(v[bell.index] - v_new)[bell.index]
            i += 1
            # if verbose and i % print_skip == 0:
            #     print(f"Error at iteration {i} is {error}.")
            v = v_new

        if error > tol:
            print(f"{bell.name} failed to converge for k={bell.k}, α = {bell.α},σ ={bell.σ}, i_a={bell.i_a}, and modified θ = {bell.θ + bell.m * (1-bell.θ)}!")
        elif verbose:
            print(f"Converged in {i} iterations.")
            print(f"Effective k and new c {np.around(bell.grid[bell.index],3),v_greedy[bell.index]}")
            

        return v_greedy[bell.index],v[bell.index]
    
    model_graph['wealth_consumption'], model_graph['i_a'], model_graph['m'] = torch.zeros(9),torch.zeros(9),torch.zeros(9)
    for i in range(model_params['number_agents']):
        agentinfo = {'u':utility, 'f':income_function, 'β':model_params['discount'], 'θ':model_graph['theta'][i], '𝛿':model_params['depreciation'], 'σ':model_graph['sigma'][i].numpy(), 'α': model_graph['alpha'][i],'k':model_graph['wealth'][i],'adapt': model_graph['a_table'][i]}
        model_graph['wealth_consumption'][i], model_graph['i_a'][i], model_graph['m'][i] = which_bellman(agentinfo)
    print(model_graph)

modelpar={'discount':0.95,'depreciation':0.08,'number_agents':9,'tech_gamma': torch.tensor([0.3,0.35,0.45]),'tech_cost': torch.tensor([0,0.15,0.65]),'num_nodes':9}        
ndata={'theta':torch.tensor([0.7603, 0.7641, 0.9275, 0.7906, 0.7858, 0.7832, 0.3904, 0.3924, 0.7884]),'sigma':torch.tensor([1.3000, 1.8000, 0.6000, 0.7000, 1.2000, 1.1000, 0.7000, 1.8000, 1.4000]),'alpha':torch.tensor([0.9952, 1.1045, 1.0706, 1.0489, 1.0576, 1.1922, 1.0162, 1.0938, 1.1324]),'wealth':torch.tensor([0.9998, 1.1309, 1.1439, 1.0342, 1.2321, 1.0819, 1.0326, 1.1193, 1.0707]), 'a_table':torch.stack([torch.tensor([0,0.5,0.9]),torch.tensor([0,0.25,0.45])]).repeat(modelpar['number_agents'],1,1)}
_optimized_wealth_consumption(ndata,modelpar)



{'theta': tensor([0.7603, 0.7641, 0.9275, 0.7906, 0.7858, 0.7832, 0.3904, 0.3924, 0.7884]), 'sigma': tensor([1.3000, 1.8000, 0.6000, 0.7000, 1.2000, 1.1000, 0.7000, 1.8000, 1.4000]), 'alpha': tensor([0.9952, 1.1045, 1.0706, 1.0489, 1.0576, 1.1922, 1.0162, 1.0938, 1.1324]), 'wealth': tensor([0.9998, 1.1309, 1.1439, 1.0342, 1.2321, 1.0819, 1.0326, 1.1193, 1.0707]), 'a_table': tensor([[[0.0000, 0.5000, 0.9000],
         [0.0000, 0.2500, 0.4500]],

        [[0.0000, 0.5000, 0.9000],
         [0.0000, 0.2500, 0.4500]],

        [[0.0000, 0.5000, 0.9000],
         [0.0000, 0.2500, 0.4500]],

        [[0.0000, 0.5000, 0.9000],
         [0.0000, 0.2500, 0.4500]],

        [[0.0000, 0.5000, 0.9000],
         [0.0000, 0.2500, 0.4500]],

        [[0.0000, 0.5000, 0.9000],
         [0.0000, 0.2500, 0.4500]],

        [[0.0000, 0.5000, 0.9000],
         [0.0000, 0.2500, 0.4500]],

        [[0.0000, 0.5000, 0.9000],
         [0.0000, 0.2500, 0.4500]],

        [[0.0000, 0.5000, 0.9000],
         [0.

In [162]:

class torchInterp1d:
    """
    PyTorch-friendly, 1-D linear interpolation.
    """
    def __init__(self, x, y):
        self.x = x
        self.y = y
       

    def __call__(self, x_target):
        x = self.x
        y = self.y

        y_target = torch.empty_like(x_target)

        for i, x_val in enumerate(x_target):
            if x_val < x[0]:
                x_1,y_1,x_2,y_2 = x[0],y[0],x[1],y[1]
                y_base,x_base = y[0], x[0] 
            elif x_val > x[-1]:
                x_1,y_1,x_2,y_2=x[-2],y[-2],x[-1],y[-1]
                y_base,x_base = y[-1],x[-1]
            else:
                ind = torch.searchsorted(x, x_val)
                if ind==14:
                    print(x)
                    print(y)
                    print(x_val)
                x_1,y_1,x_2,y_2 = x[ind-1],y[ind-1],x[ind],y[ind]
                y_base,x_base=y[ind-1],x[ind-1]


            y_target[i] = y_base + (x_val - x_base) * (y_2-y_1)/(x_2-x_1)

        return y_target







startgrid=torch.tensor([1.0e-7,1,2,3,4,5,6,7,8,9,10,k+100])

ind=torch.searchsorted(startgrid, k)
grid=torch.cat((startgrid[:ind],torch.tensor([k*0.99999, k]),
                        startgrid[ind:]))



v_array =grid/3
print(type(v_array))
print(type(grid))
v = interp1d(grid, v_array, bounds_error=False, 
            fill_value="extrapolate")
print(v(1.1),v(1600))


v = torchInterp1d(grid, v_array)
print(v(torch.tensor([1.1,1600])))



<class 'torch.Tensor'>
<class 'torch.Tensor'>
0.3666666775941849 533.3333016633987
tensor([3.6667e-01, 5.3333e+02])


In [174]:

def income_function(k,α,tech): 
    f=α * k.unsqueeze(-1)**tech['gamma'] - tech['cost']
    return torch.max(f,-1)[0]

class TensBellmanEquation:
    #Adapted from: https://python.quantecon.org/optgrowth.html
    def __init__(self,
                u,            # utility function
                f,            # production function
                k,            # current state k_t
                θ,            # given shock factor θ
                σ,            # risk averseness
                α,            # human capital
                i_a,          # adaptation investment
                m,            # protection multiplier
                β,            # discount factor
                𝛿,            # depreciation factor 
                tech):       # adaptation table 
                #name="BellmanNarrowExtended"
                

        self.u, self.f, self.k, self.β, self.θ, self.𝛿, self.σ, self.α, self.i_a, self.m, self.tech = u, f, k, β, θ, 𝛿, σ, α, i_a, m, tech

        # Set up grid
        
        startgrid=torch.tensor([1.0e-7,1,2,3,4,5,6,7,8,9,10,k+100])

        ind=torch.searchsorted(startgrid, k)
        self.grid=torch.cat((startgrid[:ind],torch.tensor([k*0.99999, k]),
                                startgrid[ind:]))

        self.grid=self.grid[self.grid>i_a]
        # Identify target state k
        self.index = torch.searchsorted(self.grid, k)-1
    def value(self, c, y, v_array):
        """
        Right hand side of the Bellman equation.
        """

        u, f, β, θ, 𝛿, σ, α, i_a, m, tech = self.u, self.f, self.β, self.θ, self.𝛿, self.σ, self.α, self.i_a, self.m, self.tech

        v = torchInterp1d(self.grid, v_array)

        return u(c,σ) + β * v((θ + m * (1-θ)) * (f(y,α,tech) - c - i_a + (1 - 𝛿) * y))



def _torch_optimized_wealth_consumption(model_graph, model_params):
    
   




    def torchmaximize(g, a, b, args):
        """
        Maximize the function g over the interval [a, b] using PyTorch's LBFGS optimizer.

        The tuple args collects any extra arguments to g.

        Returns the maximal value and the maximizer.
        """

        # Define a closure function  to reset gradient, determine value, and calculate new gradient
        def closure():
            optimizer.zero_grad()
            value = -g(x, *args)
            loss= torch.sum(value)
            loss.backward(retain_graph=True)
            return loss

        # Initial guess for consumption
        x = (args[0]/3).clone().requires_grad_(True)

        # Feed it to optimizer and keep x guesses in the bounds
        optimizer = torch.optim.LBFGS([x], history_size=10, max_iter=4)
        x.data = torch.clamp(x, a, b)

        #history=[]
        # Run optimization for 30 epochs:
        for epoch in range(30):
            running_loss = 0.0

            for i, c in enumerate(x):  # You can adjust the number of optimization steps
                #history.append(g(x,*args))
                optimizer.step(closure)
                loss = closure()
                running_loss += loss.item()

            print(f"Epoch: {epoch + 1:02}/{30} Loss: {running_loss:.5e}")



        maximizer = x
        maximum = -g(x, *args)
        print(maximizer)
        print(maximum)
        #print(history)
        return maximizer, maximum

    def utility(c, σ, type="isoelastic"):
        if type == "isoelastic":
            if σ ==1:
                return torch.log(c)
            else:
                return (c**(1-σ)-1)/(1-σ)

        else:
            print("Unspecified utility function!!!")


    def update_bellman(v, bell):
        """
        From: https://python.quantecon.org/optgrowth.html (similar example
        https://macroeconomics.github.io/Dynamic%20Programming.html#.ZC13-exBy3I)
        
        The Bellman operator.  Updates the guess of the value function
        and also computes a v-greedy policy.

        * bell is an instance of Bellman equation
        * v is an array representing a guess of the value function

        """
        v_new = torch.empty_like(v)
        v_greedy = torch.empty_like(v)
        
        print('checkpoint2')

        y = bell.grid
        # Maximize RHS of Bellman equation at state y
        a=torch.min(torch.transpose(torch.stack((torch.full(y.size(),1e-8),(y*0.00001)),0),0,1),1)[0]
        b=(y-bell.i_a)

        #pairs = torch.transpose(torch.stack((a,b),0),1,0).tolist()
        #boundsequence = [tuple(x) for x in pairs]

        c_star, v_max = torchmaximize(bell.value, a, b, (y, v))
            #VMG HELP! can anyone check that (1) subtracting i_a and 
            # (2) omitting any grid values less than i_a 
            # will not be problematic? The only thing I can come up with
            # is if i_a is greater than k*0.99999
            # which_bellman() now accounts for that case. Whole thing 
            # could use refinement.

        v_new = v_max
        v_greedy = c_star

        return v_greedy, v_new


    def which_bellman(agentinfo):
        """
        Solves bellman for each affordable adaptation option.
        """
        feasible=[]

        for option in torch.transpose(agentinfo['adapt'],0,1):
            if option[1]>=(income_function(agentinfo['k'],agentinfo['α'],tech={'gamma':model_params['tech_gamma'],'cost':model_params['tech_cost']})+(1 - model_params['depreciation'])*agentinfo['k'])*.99998:
                # ensures that the gridpoint
                # just below k, k*0.99999, is included
                pass
            else:
                #  print(f'working theta = {agentinfo.θ + option[0] *\
                #  (1-agentinfo.θ)}, i_a= {option[1]}, k= {agentinfo.k}')
                c,v=solve_bellman(TensBellmanEquation(u=utility, 
                                f=income_function, k=agentinfo['k'], 
                                θ=agentinfo['θ'], σ=agentinfo['σ'], 
                                α=agentinfo['α'], i_a=option[1],m=option[0],
                                β=model_params['discount'], 𝛿=model_params['depreciation'],
                                tech={'gamma':model_params['tech_gamma'],'cost':model_params['tech_cost']}))
                feasible.append([v,c,option[1],option[0]])

        best=min(feasible)

        return best[1],best[2],best[3]

    def solve_bellman(bell,
                    tol=1,
                    min_iter=10,
                    max_iter=1000,
                    verbose=False):
        """
        From: https://python.quantecon.org/optgrowth.html (similar example
        https://macroeconomics.github.io/Dynamic%20Programming.html#.ZC13-exBy3I)
        
        Solve model by iterating with the Bellman operator.

        """

        # Set up loop

        v = bell.u(bell.grid,bell.σ)  # Initial condition
        i = 0
        error = tol + 1
        while (i < max_iter and error > tol) or (i < min_iter):
            print('checkpoint1')
            v_greedy, v_new = update_bellman(v, bell)
            print('checkpoint3')
            error = torch.abs(v[bell.index] - v_new)[bell.index]
            print(error)
            i += 1
            # if verbose and i % print_skip == 0:
            #     print(f"Error at iteration {i} is {error}.")
            v = v_new

        print('checkpoint4')

        if error > tol:
            print(f"{bell.name} failed to converge for k={bell.k}, α = {bell.α},σ ={bell.σ}, i_a={bell.i_a}, and modified θ = {bell.θ + bell.m * (1-bell.θ)}!")
        elif verbose:
            print(f"Converged in {i} iterations.")
            print(f"Effective k and new c {torch.round(bell.grid[bell.index],3),v_greedy[bell.index]}")
            

        return v_greedy[bell.index],v[bell.index]



    
    model_graph['wealth_consumption'], model_graph['i_a'], model_graph['m'] = torch.zeros(9),torch.zeros(9),torch.zeros(9)
    for i in range(model_params['number_agents']):
        agentinfo = {'u':utility, 'f':income_function, 'β':model_params['discount'], 'θ':model_graph['theta'][i], '𝛿':model_params['depreciation'], 'σ':model_graph['sigma'][i].numpy(), 'α': model_graph['alpha'][i],'k':model_graph['wealth'][i],'adapt': model_graph['a_table'][i]}
        model_graph['wealth_consumption'][i], model_graph['i_a'][i], model_graph['m'][i] = which_bellman(agentinfo)
    print(model_graph)

modelpar={'discount':0.95,'depreciation':0.08,'number_agents':9,'tech_gamma': torch.tensor([0.3,0.35,0.45]),'tech_cost': torch.tensor([0,0.15,0.65]),'num_nodes':9}        
ndata={'theta':torch.tensor([0.7603, 0.7641, 0.9275, 0.7906, 0.7858, 0.7832, 0.3904, 0.3924, 0.7884]),'sigma':torch.tensor([1.3000, 1.8000, 0.6000, 0.7000, 1.2000, 1.1000, 0.7000, 1.8000, 1.4000]),'alpha':torch.tensor([0.9952, 1.1045, 1.0706, 1.0489, 1.0576, 1.1922, 1.0162, 1.0938, 1.1324]),'wealth':torch.tensor([0.9998, 1.1309, 1.1439, 1.0342, 1.2321, 1.0819, 1.0326, 1.1193, 1.0707]), 'a_table':torch.stack([torch.tensor([0,0.5,0.9]),torch.tensor([0,0.25,0.45])]).repeat(modelpar['number_agents'],1,1)}
_torch_optimized_wealth_consumption(ndata,modelpar)







checkpoint1
checkpoint2
Epoch: 01/30 Loss: 9.51646e+03
Epoch: 02/30 Loss: 9.51646e+03
Epoch: 03/30 Loss: 9.51645e+03
Epoch: 04/30 Loss: 9.51645e+03
Epoch: 05/30 Loss: 9.51644e+03
Epoch: 06/30 Loss: 9.51644e+03
Epoch: 07/30 Loss: 9.51643e+03
Epoch: 08/30 Loss: 9.51643e+03
Epoch: 09/30 Loss: 9.51642e+03
Epoch: 10/30 Loss: 9.51642e+03
Epoch: 11/30 Loss: 9.51641e+03
Epoch: 12/30 Loss: 9.51641e+03
Epoch: 13/30 Loss: 9.51640e+03
Epoch: 14/30 Loss: 9.51640e+03
Epoch: 15/30 Loss: 9.51639e+03
Epoch: 16/30 Loss: 9.51639e+03
Epoch: 17/30 Loss: 9.51638e+03
Epoch: 18/30 Loss: 9.51638e+03
Epoch: 19/30 Loss: 9.51637e+03
Epoch: 20/30 Loss: 9.51637e+03
Epoch: 21/30 Loss: 9.51636e+03
Epoch: 22/30 Loss: 9.51636e+03
Epoch: 23/30 Loss: 9.51635e+03
Epoch: 24/30 Loss: 9.51635e+03
Epoch: 25/30 Loss: 9.51634e+03
Epoch: 26/30 Loss: 9.51634e+03
Epoch: 27/30 Loss: 9.51634e+03
Epoch: 28/30 Loss: 9.51633e+03
Epoch: 29/30 Loss: 9.51633e+03
Epoch: 30/30 Loss: 9.51632e+03
tensor([ 1.0000,  0.3333,  0.3333,  0.3333,  0

IndexError: index 14 is out of bounds for dimension 0 with size 14

In [135]:
base=torch.tensor([1.0000e-07, 1.0100e+02])
coef=torch.tensor(0.9952)
powers=torch.tensor([0.3000, 0.3500, 0.4500])
cost=torch.tensor([0,0.15,0.65])
#powers=torch.transpose(powers,-1,0)#.repeat(4,1)
print(powers.dtype)
print(base.dtype)
print(coef.dtype)
r1=coef * base[:, None] ** powers - cost
torch.max(r1,-1)[0]



torch.float32
torch.float32
torch.float32


tensor([0.0079, 7.2906])

In [ ]:

def income_function(k,α,tech): 
    f=α * k.unsqueeze(-1)**tech['gamma'] - tech['cost']
    return torch.max(f,-1)[0]

class TensBellmanEquation:
    #Adapted from: https://python.quantecon.org/optgrowth.html
    def __init__(self,
                u,            # utility function
                f,            # production function
                k,            # current state k_t
                θ,            # given shock factor θ
                σ,            # risk averseness
                α,            # human capital
                i_a,          # adaptation investment
                m,            # protection multiplier
                β,            # discount factor
                𝛿,            # depreciation factor 
                tech):       # adaptation table 
                #name="BellmanNarrowExtended"
                

        self.u, self.f, self.k, self.β, self.θ, self.𝛿, self.σ, self.α, self.i_a, self.m, self.tech = u, f, k, β, θ, 𝛿, σ, α, i_a, m, tech

        # Set up grid
        
        startgrid=torch.tensor([1.0e-7,1,2,3,4,5,6,7,8,9,10,k+100])

        ind=torch.searchsorted(startgrid, k)
        self.grid=torch.cat((startgrid[:ind],torch.tensor([k*0.99999, k]),
                                startgrid[ind:]))

        self.grid=self.grid[self.grid>i_a]
        # Identify target state k
        self.index = torch.searchsorted(self.grid, k)-1
    def value(self, c, y, v_array):
        """
        Right hand side of the Bellman equation.
        """

        u, f, β, θ, 𝛿, σ, α, i_a, m, tech = self.u, self.f, self.β, self.θ, self.𝛿, self.σ, self.α, self.i_a, self.m, self.tech

        v = torchInterp1d(self.grid, v_array)

        return u(c,σ) + β * v((θ + m * (1-θ)) * (f(y,α,tech) - c - i_a + (1 - 𝛿) * y))



def _torch_optimized_wealth_consumption(model_graph, model_params):
    
   




    def torchmaximize(g, a, b, args):
        """
        Maximize the function g over the interval [a, b] using PyTorch's LBFGS optimizer.

        The tuple args collects any extra arguments to g.

        Returns the maximal value and the maximizer.
        """

        # Define a closure function  to reset gradient, determine value, and calculate new gradient
        def closure():
            optimizer.zero_grad()
            value = -g(x, *args)
            loss= torch.sum(value)
            loss.backward(retain_graph=True)
            return loss

        # Initial guess for consumption
        x = (args[0]/3).clone().requires_grad_(True)

        # Feed it to optimizer and keep x guesses in the bounds
        optimizer = torch.optim.LBFGS([x], history_size=10, max_iter=4)
        x.data = torch.clamp(x, a, b)

        #history=[]
        # Run optimization for 30 epochs:
        for epoch in range(30):
            running_loss = 0.0

            for i, c in enumerate(x):  # You can adjust the number of optimization steps
                #history.append(g(x,*args))
                optimizer.step(closure)
                loss = closure()
                running_loss += loss.item()

            print(f"Epoch: {epoch + 1:02}/{30} Loss: {running_loss:.5e}")



        maximizer = x
        maximum = -g(x, *args)
        print(maximizer)
        print(maximum)
        #print(history)
        return maximizer, maximum

    def utility(c, σ, type="isoelastic"):
        if type == "isoelastic":
            if σ ==1:
                return torch.log(c)
            else:
                return (c**(1-σ)-1)/(1-σ)

        else:
            print("Unspecified utility function!!!")


    def update_bellman(v, bell):
        """
        From: https://python.quantecon.org/optgrowth.html (similar example
        https://macroeconomics.github.io/Dynamic%20Programming.html#.ZC13-exBy3I)
        
        The Bellman operator.  Updates the guess of the value function
        and also computes a v-greedy policy.

        * bell is an instance of Bellman equation
        * v is an array representing a guess of the value function

        """
        v_new = torch.empty_like(v)
        v_greedy = torch.empty_like(v)
        
        print('checkpoint2')

        y = bell.grid
        # Maximize RHS of Bellman equation at state y
        a=torch.min(torch.transpose(torch.stack((torch.full(y.size(),1e-8),(y*0.00001)),0),0,1),1)[0]
        b=(y-bell.i_a)

        #pairs = torch.transpose(torch.stack((a,b),0),1,0).tolist()
        #boundsequence = [tuple(x) for x in pairs]

        c_star, v_max = torchmaximize(bell.value, a, b, (y, v))
            #VMG HELP! can anyone check that (1) subtracting i_a and 
            # (2) omitting any grid values less than i_a 
            # will not be problematic? The only thing I can come up with
            # is if i_a is greater than k*0.99999
            # which_bellman() now accounts for that case. Whole thing 
            # could use refinement.

        v_new = v_max
        v_greedy = c_star

        return v_greedy, v_new


    def which_bellman(agentinfo):
        """
        Solves bellman for each affordable adaptation option.
        """
        feasible=[]

        for option in torch.transpose(agentinfo['adapt'],0,1):
            if option[1]>=(income_function(agentinfo['k'],agentinfo['α'],tech={'gamma':model_params['tech_gamma'],'cost':model_params['tech_cost']})+(1 - model_params['depreciation'])*agentinfo['k'])*.99998:
                # ensures that the gridpoint
                # just below k, k*0.99999, is included
                pass
            else:
                #  print(f'working theta = {agentinfo.θ + option[0] *\
                #  (1-agentinfo.θ)}, i_a= {option[1]}, k= {agentinfo.k}')
                c,v=solve_bellman(TensBellmanEquation(u=utility, 
                                f=income_function, k=agentinfo['k'], 
                                θ=agentinfo['θ'], σ=agentinfo['σ'], 
                                α=agentinfo['α'], i_a=option[1],m=option[0],
                                β=model_params['discount'], 𝛿=model_params['depreciation'],
                                tech={'gamma':model_params['tech_gamma'],'cost':model_params['tech_cost']}))
                feasible.append([v,c,option[1],option[0]])

        best=min(feasible)

        return best[1],best[2],best[3]

    def solve_bellman(bell,
                    tol=1,
                    min_iter=10,
                    max_iter=1000,
                    verbose=False):
        """
        From: https://python.quantecon.org/optgrowth.html (similar example
        https://macroeconomics.github.io/Dynamic%20Programming.html#.ZC13-exBy3I)
        
        Solve model by iterating with the Bellman operator.

        """

        # Set up loop

        v = bell.u(bell.grid,bell.σ)  # Initial condition
        i = 0
        error = tol + 1
        while (i < max_iter and error > tol) or (i < min_iter):
            print('checkpoint1')
            v_greedy, v_new = update_bellman(v, bell)
            print('checkpoint3')
            error = torch.abs(v[bell.index] - v_new)[bell.index]
            print(error)
            i += 1
            # if verbose and i % print_skip == 0:
            #     print(f"Error at iteration {i} is {error}.")
            v = v_new

        print('checkpoint4')

        if error > tol:
            print(f"{bell.name} failed to converge for k={bell.k}, α = {bell.α},σ ={bell.σ}, i_a={bell.i_a}, and modified θ = {bell.θ + bell.m * (1-bell.θ)}!")
        elif verbose:
            print(f"Converged in {i} iterations.")
            print(f"Effective k and new c {torch.round(bell.grid[bell.index],3),v_greedy[bell.index]}")
            

        return v_greedy[bell.index],v[bell.index]



    
    model_graph['wealth_consumption'], model_graph['i_a'], model_graph['m'] = torch.zeros(9),torch.zeros(9),torch.zeros(9)
    for i in range(model_params['number_agents']):
        agentinfo = {'u':utility, 'f':income_function, 'β':model_params['discount'], 'θ':model_graph['theta'][i], '𝛿':model_params['depreciation'], 'σ':model_graph['sigma'][i].numpy(), 'α': model_graph['alpha'][i],'k':model_graph['wealth'][i],'adapt': model_graph['a_table'][i]}
        model_graph['wealth_consumption'][i], model_graph['i_a'][i], model_graph['m'][i] = which_bellman(agentinfo)
    print(model_graph)

modelpar={'discount':0.95,'depreciation':0.08,'number_agents':9,'tech_gamma': torch.tensor([0.3,0.35,0.45]),'tech_cost': torch.tensor([0,0.15,0.65]),'num_nodes':9}        
ndata={'theta':torch.tensor([0.7603, 0.7641, 0.9275, 0.7906, 0.7858, 0.7832, 0.3904, 0.3924, 0.7884]),'sigma':torch.tensor([1.3000, 1.8000, 0.6000, 0.7000, 1.2000, 1.1000, 0.7000, 1.8000, 1.4000]),'alpha':torch.tensor([0.9952, 1.1045, 1.0706, 1.0489, 1.0576, 1.1922, 1.0162, 1.0938, 1.1324]),'wealth':torch.tensor([0.9998, 1.1309, 1.1439, 1.0342, 1.2321, 1.0819, 1.0326, 1.1193, 1.0707]), 'a_table':torch.stack([torch.tensor([0,0.5,0.9]),torch.tensor([0,0.25,0.45])]).repeat(modelpar['number_agents'],1,1)}
_torch_optimized_wealth_consumption(ndata,modelpar)





